# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

env:
  - DJANGO=https://github.com/django/django/archive/master.tar.gz
  - DJANGO=django>=1.6,<1.7
  - DJANGO=django>=1.5,<1.6

install:
  - pip install $DJANGO
  - pip install -r requirements-test.txt --use-mirrors

script:
  - coverage run --source gcse runtests.py
  - coverage report

# report coverage to coveralls.io
after_success: 
  - coveralls
